title: Video Processing | Graphics and Multimedia Laboratory CMC MSU
email: info@compression.ru
description: >-
  Everything about video processing: codecs, filters, quality measures, matting, completion.
  MSU CMC, Graphics and Multimedia Laboratory, Video Group
baseurl: ""
url: "https://videoprocessing.ml"
google_analytics: 'UA-15281510-2'

collections:
  projects:
    output: true
  subprojects:
    output: true
  carousel:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tag: visible
      see_also: []
  - scope:
      path: "_posts/benchmarks"
    values:
      permalink: /benchmarks/:categories/:title:output_ext
      project: benchmarks

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-youtube
  - jekyll-tidy

exclude:
  - .idea
  - vendor  # for GitLab CI
  - .sass-cache
  - README.md
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  per_page: 24
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  tag: visible
